# Generated by Django 4.0.4 on 2022-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_directores', '0002_pelicula_alter_director_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion',
            new_name='sinopsis',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='titulo',
            new_name='título',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(),
        ),
    ]
